name: novaplayer
description: A simple music player app
version: 1.0.0+1

environment:
  sdk: ">=2.17.0 <3.0.0"

dependencies:
  flutter:
    sdk: flutter
  permission_handler: ^10.4.0
  on_audio_query: ^2.6.4
  just_audio: ^0.9.30

flutter:
  uses-material-design: true